import smtplib

my_email=""
password=""

#Establish connection 
connection=smtplib.SMTP("smtp.gmail.com")

#Secure your connection
connection.starttls()

#Now need to login
connection.login(user=my_email,password=password)

#Now send email
connection.sendmail(from_addr=my_email,to_addrs="tutejaanmol54@gmail.com",msg="Hello : This is autogenerated Python message")

#Close your connection
connection.close()